# fichier qui permet de noter les instructions pour créer l'image d'un container

# Je me base sur quelle image?

FROM nginx

# Paramétrage des ports
EXPOSE 80:80

#je copie le contenu du repertoire de mon Dockerfile dans /usr/share/nginx/html (le repertoire servit par nginx)
COPY . /usr/share/nginx/html

